default_platform(:android)

platform :android do
  desc "Deploy to internal testers on Google Play"
  lane :internal do
    gradle(task: "clean bundleRelease")
    
    upload_to_play_store(
      track: 'internal',
      release_status: 'draft',
      skip_upload_metadata:true
      
    )
  end

  desc "validate service account key"
  lane :validate do
  validate_play_store_json_key(
      json_key: 'json secret file'
    )
  end

  desc "Deploy a new version to the Google Play Production release"
  lane :production do
    gradle(
      task: 'assemble', 
      build_type: 'Release'
      )

    upload_to_play_store(
      track: 'production',
     skip_upload_metadata: true)

     slack(message: 'Successfully distributed a new beta build')

  end

end
